#!/bin/bash

errcho () {
    (echo "${@}" >&2)
}

errcho -n "${1}: "
if [ -t 1 ]; then
    errcho ""
fi

tmp="$(mktemp)"
sed 's/</\n</g' "${1}" > "${tmp}"

img_url_1="$(grep -m 1 "<img" "${tmp}" | cut -d\' -f2)"
img_url_2="$(grep -m 2 "<img" "${tmp}" | tail -n 1 | cut -d\' -f2)"
if [ "${img_url_2}" == "${img_url_1}" ]; then
    img_url_2=""
fi

cemetery="$(grep "<h1>" "${tmp}" | cut -d\> -f2)"
position="$(grep "Sijainti" "${tmp}" | cut -d\  -f2-)"

tmp_people="$(mktemp)"
awk "/<td align='center'>/ { show=1 } show; /<\/td>/ { show=0 }" "${tmp}" > "${tmp_people}"

people=()

name=""
birthdate=""
birthplace=""
deathdate=""
deathplace=""

function set_birth() {
    line="${1}"
    birth="$(echo "${line}" | cut -d\> -f2-)"
    birthdate="${birth#\*}"
    birthdate="${birthdate# }"
    birthdate="$(echo "${birthdate}" | cut -d\  -f 1)"
    birthplace="$(echo "${birth}" | cut -d\  -f2-)"
    if [ "${birthplace}" == "${birthdate}" ]; then
        birthplace=""
    fi

}


function set_death() {
    line="${1}"
    deathdate="$(echo "${line}" | cut -d\  -f2)"
    deathplace="$(echo "${line}" | cut -d\  -f3-)"

}


while read -r line; do
    if [[ "${line}" == "<td"* ]]; then
        continue
    elif [[ "${line}" == "<br>Sijainti"* ]]; then
        continue
    elif [[ "${line}" == "</b>"* ]]; then
        break
    elif [[ "${line}" =~ ^\<br\>[\*0-9] ]]; then
        set_birth "${line}"
    elif [[ "${line}" == "<br>&#134;"* ]]; then
        set_death "${line}"
    else
        if [ ! -z "${name}" ]; then
            birth="${birthdate}\",\"${birthplace}"
            death="${deathdate}\",\"${deathplace}"
            people+=("${name}\",\"${birth}\",\"${death}")
            birthdate=""
            birthplace=""
            deathdate=""
            deathplace=""
        fi
        name="$(echo "${line}" | cut -d\> -f2)"
    fi
done < "${tmp_people}"

if [ -z "${name}" ]; then
    errcho "WARNING: failed to read name from ${1}"
fi

birth="${birthdate}\",\"${birthplace}"
death="${deathdate}\",\"${deathplace}"
people+=("${name}\",\"${birth}\",\"${death}")

for person in "${people[@]}"; do
    echo "\"${person}\",\"${cemetery}\",\"${position}\",\"${img_url_1}\",\"${img_url_2}\""
done

rm "${tmp}" "${tmp_people}"

if [ -t 1 ]; then
    errcho -n "${1} "
fi

errcho "done."

