#!/bin/bash

my_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
sukukuvat="${my_dir}/sukukuvat"
number_of_files="$(ls -f | wc -l)"

i=1
files="${@:-*.html}"
for f in ${files}; do
    printf "\r%${#number_of_files}d / ${number_of_files}" "${i}"
    number_of_lines="$(bash "${sukukuvat}" "${f}" 2>/dev/null | wc -l)"
    if [ "${number_of_lines}" -lt 1 ]; then
        echo ""
        echo -e "\033[1mnumber of output lines less than 1: ${f}\033[0m"
        bash "${sukukuvat}" "${f}"
        exit 1
    fi
    i=$((i + 1))
done

echo ""
echo "all done, no issues"

